In [1]:
# пустой кортеж:
()

()

In [2]:
# кортеж из элементов типа String:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [3]:
# кортеж из целых чисел:
x1 = (1, 2, 3)

(1, 2, 3)

In [5]:
# кортеж из элементов разных типов: 
x2 = (1, 2.0, "tmp")

(1, 2.0, "tmp")

In [6]:
# именованный кортеж:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

In [7]:
# длина кортежа x2:
length(x2)

3

In [8]:
# обратиться к элементам кортежа x2:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [9]:
# произвести какую-либо операцию (сложение)
# с вторым и третьим элементами кортежа x1:
с = x1[2] + x1[3]

5

In [10]:
# обращение к элементам именованного кортежа x3: 
x3.a, x3.b, x3[2]

(2, 3, 3)

In [11]:
# проверка вхождения элементов tmp и 0 в кортеж x2 
# (два способа обращения к методу in()):
in("tmp", x2), 0 in x2

(true, false)

In [23]:
# создать словарь с именем phonebook:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), 
    "Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [13]:
# вывести ключи словаря:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [14]:
# вывести значения элементов словаря:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [15]:
# вывести заданные в словаре пары "ключ - значение":
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [16]:
# проверка вхождения ключа в словарь:
haskey(phonebook, "Иванов И.И.")

true

In [24]:
# добавить элемент в словарь:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [25]:
# удалить ключ и связанные с ним значения из словаря
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [26]:
# Объединение словарей (функция merge()):
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

In [27]:
# создать множество из четырёх целочисленных значений:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [28]:
# создать множество из 11 символьных значений:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [29]:
# проверка эквивалентности двух множеств:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [30]:
S3 = Set([1,2,2,3,1,2,3,2,1]); 
S4 = Set([2,3,1]); 
issetequal(S3,S4)

true

In [31]:
# объединение множеств:
C=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [32]:
# пересечение множеств:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [33]:
# разность множеств:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [34]:
# проверка вхождения элементов одного множества в другое:
issubset(S1,S4)

true

In [35]:
# добавление элемента в множество:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [36]:
# удаление последнего элемента множества:
pop!(S4)

2

In [37]:
# создание пустого массива с абстрактным типом:
empty_array_1 = []

Any[]

In [39]:
# создание пустого массива с конкретным типом: 
empty_array_2 = (Int64)[]

Int64[]

In [40]:
empty_array_3 = (Float64)[]

Float64[]

In [41]:
# вектор-столбец:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [42]:
# вектор-строка:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [43]:
# многомерные массивы (матрицы):
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [44]:
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [45]:
# одномерный массив из 8 элементов (массив $1 \times 8$)
# со значениями, случайно распределёнными на интервале [0, 1):
c = rand(1,8)

1×8 Matrix{Float64}:
 0.209468  0.4564  0.716093  0.980613  …  0.0162479  0.548266  0.456862

In [46]:
# многомерный массив $2 \times 3$ (2 строки, 3 столбца) элементов
# со значениями, случайно распределёнными на интервале [0, 1):
C = rand(2,3);

In [47]:
C

2×3 Matrix{Float64}:
 0.113001   0.941538  0.804419
 0.0108865  0.935917  0.653456

In [48]:
# трёхмерный массив:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.324993  0.920096   0.0513952
 0.328887  0.0933765  0.0491648
 0.879014  0.2423     0.362187
 0.583426  0.360941   0.213788

[:, :, 2] =
 0.483531  0.347641  0.669412
 0.095872  0.656512  0.402238
 0.609596  0.412485  0.296019
 0.133062  0.652427  0.532998

In [49]:
# массив из квадратных корней всех целых чисел от 1 до 10:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [50]:
# массив с элементами вида 3*x^2,
# где x - нечётное число от 1 до 9 (включительно)
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [51]:
# массив квадратов элементов, если квадрат не делится на 5 или 4:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

In [52]:
# одномерный массив из пяти единиц:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [53]:
# двумерный массив 2x3 из единиц:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [54]:
# одномерный массив из 4 нулей:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [55]:
# заполнить массив 3x2 цифрами 3.5
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [56]:
# заполнение массива посредством функции repeat():
repeat([1,2],3,3)
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [57]:
# преобразование одномерного массива из целых чисел от 1 до 12
# в двумерный массив  2x6
a = collect(1:12)
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [58]:
# транспонирование
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [59]:
# транспонирование
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [60]:
#  массив 10x5 целых чисел в диапазоне [10, 20]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 14  14  16  11  17
 20  11  17  15  16
 18  11  13  19  11
 19  13  13  18  10
 17  17  16  19  18
 14  18  19  14  15
 20  19  12  14  16
 12  17  11  13  15
 11  15  15  15  12
 16  10  11  15  20

In [61]:
# выбор всех значений строки в столбце 2:
ar[:, 2]

10-element Vector{Int64}:
 14
 11
 11
 13
 17
 18
 19
 17
 15
 10

In [62]:
# выбор всех значений в столбцах 2 и 5:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 14  17
 11  16
 11  11
 13  10
 17  18
 18  15
 19  16
 17  15
 15  12
 10  20

In [63]:
# все значения строк в столбцах 2, 3 и 4:
ar[:, 2:4]

10×3 Matrix{Int64}:
 14  16  11
 11  17  15
 11  13  19
 13  13  18
 17  16  19
 18  19  14
 19  12  14
 17  11  13
 15  15  15
 10  11  15

In [64]:
# значения в строках 2, 4, 6 и в столбцах 1 и 5:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 20  16
 19  10
 14  15

In [65]:
# значения в строке 1 от столбца 3 до последнего столбца: 
ar[1, 3:end]

3-element Vector{Int64}:
 16
 11
 17

In [66]:
# сортировка по столбцам:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 11  10  11  11  10
 12  11  11  13  11
 14  11  12  14  12
 14  13  13  14  15
 16  14  13  15  15
 17  15  15  15  16
 18  17  16  15  16
 19  17  16  18  17
 20  18  17  19  18
 20  19  19  19  20

In [67]:
# сортировка по строкам:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 11  14  14  16  17
 11  15  16  17  20
 11  11  13  18  19
 10  13  13  18  19
 16  17  17  18  19
 14  14  15  18  19
 12  14  16  19  20
 11  12  13  15  17
 11  12  15  15  15
 10  11  15  16  20

In [68]:
# поэлементное сравнение с числом
# (результат - массив логических значений):
ar .> 14

10×5 BitMatrix:
 0  0  1  0  1
 1  0  1  1  1
 1  0  0  1  0
 1  0  0  1  0
 1  1  1  1  1
 0  1  1  0  1
 1  1  0  0  1
 0  1  0  0  1
 0  1  1  1  0
 1  0  0  1  1

In [69]:
# возврат индексов элементов массива, удовлетворяющих условию:
findall(ar .> 14)

29-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(4, 1)
 CartesianIndex(5, 1)
 CartesianIndex(7, 1)
 CartesianIndex(10, 1)
 CartesianIndex(5, 2)
 CartesianIndex(6, 2)
 CartesianIndex(7, 2)
 CartesianIndex(8, 2)
 CartesianIndex(9, 2)
 CartesianIndex(1, 3)
 CartesianIndex(2, 3)
 ⋮
 CartesianIndex(3, 4)
 CartesianIndex(4, 4)
 CartesianIndex(5, 4)
 CartesianIndex(9, 4)
 CartesianIndex(10, 4)
 CartesianIndex(1, 5)
 CartesianIndex(2, 5)
 CartesianIndex(5, 5)
 CartesianIndex(6, 5)
 CartesianIndex(7, 5)
 CartesianIndex(8, 5)
 CartesianIndex(10, 5)

In [ ]:
# ЗАДАНИЯ ДЛЯ САМОСТОЯТЕЛЬНОЙ РАБОТЫ

In [71]:
#1.
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])

AandB = intersect(A,B)
AandC = intersect(A,C)
BandC = intersect(B,C)

p1 = union(AandB, AandB)
p2 = union(p1, AandC)

P = union(p2, BandC)

Set{Int64} with 6 elements:
  0
  4
  7
  9
  3
  1

In [72]:
#2.
Q = Set([1, 2, 3, 4])
W = Set([1.0, 3.3, 7.6])
E = Set("qwerty")

Set{Char} with 6 elements:
  'w'
  'y'
  'e'
  'r'
  't'
  'q'

In [73]:
issetequal(Q,W)

false

In [74]:
union(Q,W,E)

Set{Any} with 12 elements:
  'w'
  7.6
  'e'
  1.0
  4
  2
  'y'
  3.3
  'r'
  't'
  3
  'q'

In [75]:
intersect(Q,W)

Set{Float64} with 1 element:
  1.0

In [76]:
setdiff(Q,W)

Set{Int64} with 3 elements:
  4
  2
  3

In [77]:
issubset(Q,W)

false

In [78]:
push!(E, 'u')

Set{Char} with 7 elements:
  'w'
  'y'
  'u'
  'e'
  'r'
  't'
  'q'

In [79]:
pop!(E)

'w': ASCII/Unicode U+0077 (category Ll: Letter, lowercase)

In [80]:
#3.
#1) N=21
[i for i in 1:21]

21-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21

In [81]:
collect(1:21)

21-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21

In [83]:
#2)
[i for i in 21:-1:1]

21-element Vector{Int64}:
 21
 20
 19
 18
 17
 16
 15
 14
 13
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

In [85]:
sort(collect(1:21), rev=true)

21-element Vector{Int64}:
 21
 20
 19
 18
 17
 16
 15
 14
 13
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

In [163]:
#3)
append!(collect(1:21), sort(collect(1:20), rev = true))

41-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
  ⋮
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

In [164]:
append!([i for i in 1:21], [j for j in 20:-1:1])

41-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
  ⋮
 12
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
  1

In [91]:
#4)
tmp = rand(4,6,3)

4×6×3 Array{Float64, 3}:
[:, :, 1] =
 0.22539    0.823737   0.665588  0.867232   0.0812585  0.771429
 0.0298163  0.23293    0.0968    0.740822   0.698985   0.000895025
 0.688696   0.0922611  0.24061   0.994667   0.254193   0.751649
 0.91861    0.642699   0.152821  0.0233591  0.990343   0.909852

[:, :, 2] =
 0.167417  0.147863  0.633164  0.860159  0.281131   0.335424
 0.870791  0.351263  0.218078  0.890443  0.0787401  0.0345359
 0.902846  0.036589  0.555971  0.844363  0.206415   0.976347
 0.592511  0.676162  0.399539  0.904641  0.250451   0.907981

[:, :, 3] =
 0.485854  0.819319   0.0303418  0.748488   0.983264  0.0732588
 0.213279  0.395082   0.132885   0.877686   0.328408  0.822766
 0.42471   0.0617085  0.707469   0.225382   0.59201   0.227713
 0.11433   0.473567   0.216158   0.0846277  0.898807  0.907894

In [92]:
tmp = rand(4*6*3)
tmp = reshape(tmp, (4,6,3))

4×6×3 Array{Float64, 3}:
[:, :, 1] =
 0.980892  0.0201232  0.514157  0.457269   0.456321  0.102833
 0.74343   0.308824   0.192523  0.960027   0.883829  0.873872
 0.707595  0.795022   0.460781  0.148293   0.570975  0.630099
 0.777631  0.123396   0.18402   0.0488513  0.919143  0.291544

[:, :, 2] =
 0.451821  0.732986  0.406866  0.920406   0.787951   0.506432
 0.956721  0.552998  0.96593   0.0517157  0.0796583  0.816998
 0.904932  0.815316  0.367541  0.973002   0.641644   0.855112
 0.331768  0.600887  0.784642  0.349721   0.898262   0.0618003

[:, :, 3] =
 0.658466  0.815065  0.787332  0.297999  0.125613  0.522754
 0.543201  0.102713  0.500018  0.019029  0.135879  0.728455
 0.921976  0.100955  0.345157  0.934015  0.499408  0.786769
 0.817066  0.528364  0.859519  0.742694  0.482367  0.777953

In [93]:
#5)
fill(tmp[1], 10)

10-element Vector{Float64}:
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434

In [95]:
repeat([tmp[1]], 10)

10-element Vector{Float64}:
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434

In [96]:
#6)
fill(tmp, 10)

10-element Vector{Array{Float64, 3}}:
 [0.9808917867288434 0.020123188447783047 … 0.45632142406202014 0.10283265015022502; 0.7434301085294002 0.30882397712043275 … 0.8838293508654596 0.8738715541593599; 0.7075951400097695 0.795022004426991 … 0.5709747571885091 0.6300990834049478; 0.7776309241296008 0.12339558195359324 … 0.9191428286758081 0.2915435501093566;;; 0.4518209596910817 0.7329861102593678 … 0.787950988756123 0.5064317764997949; 0.9567210460434802 0.5529979255726463 … 0.07965832960309915 0.8169975822798834; 0.904931736158913 0.8153164154141312 … 0.6416439865074085 0.8551119546083065; 0.33176764291879257 0.6008867207723797 … 0.8982623162985729 0.06180025049687332;;; 0.6584657350247354 0.815064943495369 … 0.12561313621353853 0.5227537178005716; 0.5432014929540012 0.10271269074213529 … 0.1358789944805312 0.7284551487825051; 0.921975735677537 0.10095473066123795 … 0.49940826113426307 0.7867694671098151; 0.8170661599847463 0.5283639758606172 … 0.48236749329329853 0.7779534900213554]

In [97]:
repeat([tmp], 10)

10-element Vector{Array{Float64, 3}}:
 [0.9808917867288434 0.020123188447783047 … 0.45632142406202014 0.10283265015022502; 0.7434301085294002 0.30882397712043275 … 0.8838293508654596 0.8738715541593599; 0.7075951400097695 0.795022004426991 … 0.5709747571885091 0.6300990834049478; 0.7776309241296008 0.12339558195359324 … 0.9191428286758081 0.2915435501093566;;; 0.4518209596910817 0.7329861102593678 … 0.787950988756123 0.5064317764997949; 0.9567210460434802 0.5529979255726463 … 0.07965832960309915 0.8169975822798834; 0.904931736158913 0.8153164154141312 … 0.6416439865074085 0.8551119546083065; 0.33176764291879257 0.6008867207723797 … 0.8982623162985729 0.06180025049687332;;; 0.6584657350247354 0.815064943495369 … 0.12561313621353853 0.5227537178005716; 0.5432014929540012 0.10271269074213529 … 0.1358789944805312 0.7284551487825051; 0.921975735677537 0.10095473066123795 … 0.49940826113426307 0.7867694671098151; 0.8170661599847463 0.5283639758606172 … 0.48236749329329853 0.7779534900213554]

In [98]:
#7)
append!(fill(tmp[1], 11), append!(fill(tmp[2], 10), fill(tmp[3], 10)))

31-element Vector{Float64}:
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.7434301085294002
 0.7434301085294002
 ⋮
 0.7434301085294002
 0.7434301085294002
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695

In [100]:
append!(repeat([tmp[1]], 11), append!(repeat([tmp[2]], 10),
        repeat([tmp[3]], 10)))

31-element Vector{Float64}:
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.7434301085294002
 0.7434301085294002
 ⋮
 0.7434301085294002
 0.7434301085294002
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695

In [101]:
append!(repeat([tmp[1], tmp[2], tmp[3]], 10), tmp[1])

31-element Vector{Float64}:
 0.9808917867288434
 0.7434301085294002
 0.7075951400097695
 0.9808917867288434
 0.7434301085294002
 0.7075951400097695
 0.9808917867288434
 0.7434301085294002
 0.7075951400097695
 0.9808917867288434
 0.7434301085294002
 0.7075951400097695
 0.9808917867288434
 ⋮
 0.7434301085294002
 0.7075951400097695
 0.9808917867288434
 0.7434301085294002
 0.7075951400097695
 0.9808917867288434
 0.7434301085294002
 0.7075951400097695
 0.9808917867288434
 0.7434301085294002
 0.7075951400097695
 0.9808917867288434

In [102]:
#8)
append!(fill(tmp[1], 10), append!(fill(tmp[2], 20), fill(tmp[3], 30)))

60-element Vector{Float64}:
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.7434301085294002
 0.7434301085294002
 0.7434301085294002
 ⋮
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695

In [103]:
append!(repeat([tmp[1]], 10), append!(repeat([tmp[2]], 20),
        repeat([tmp[3]], 30)))

60-element Vector{Float64}:
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.9808917867288434
 0.7434301085294002
 0.7434301085294002
 0.7434301085294002
 ⋮
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695
 0.7075951400097695

In [105]:
#9)
ar2 = [2^tmp[i] for i in 1:3]
ar2 = append!(ar2, fill(2^tmp[3], 3))

6-element Vector{Float64}:
 1.9736850445967162
 1.6741515232810351
 1.6330796307567377
 1.6330796307567377
 1.6330796307567377
 1.6330796307567377

In [106]:
ar2 = [2^tmp[i] for i in [1,2,3,3,3,3]]

6-element Vector{Float64}:
 1.9736850445967162
 1.6741515232810351
 1.6330796307567377
 1.6330796307567377
 1.6330796307567377
 1.6330796307567377

In [109]:
n = 0
for i in (1:length(ar2))
    t = ar2[i]
    k = 1
    if (trunc(Int,t)==0)
        k = 0
    end
    while(!(t%1==0))
        t = t*10
        k = k+1
    end
    t = trunc(Int,t)
    for i in (1:1:k)
        if (t%10==6)
            n = n+1
        end
        t = div(t, 10)
    end
end

n    

16

In [115]:
#10)
y = [exp(i)*cos(i) for i in 3:0.1:6]

31-element Vector{Float64}:
 -19.884530844146987
 -22.178753389342127
 -24.490696732801293
 -26.77318244299338
 -28.969237768093574
 -31.011186439374516
 -32.819774760338504
 -34.30336011037369
 -35.35719361853035
 -35.86283371230767
 -35.68773248011913
 -34.68504225166807
 -32.693695428321746
   ⋮
  25.046704998273004
  42.09920106253839
  61.99663027669454
  84.92906736250268
 111.0615860420258
 140.5250750527875
 173.40577640857734
 209.73349424783467
 249.46844055885668
 292.4867067371223
 338.5643778585117
 387.36034029093076

In [116]:
sum(y)/length(y)

53.11374594642971

In [117]:
#11)
x = 0.1
y = 0.2

[[x^i y^(i-2)] for i in 3:3:36]

12-element Vector{Matrix{Float64}}:
 [0.0010000000000000002 0.2]
 [1.0000000000000004e-6 0.0016000000000000003]
 [1.0000000000000005e-9 1.2800000000000006e-5]
 [1.0000000000000008e-12 1.0240000000000006e-7]
 [1.0000000000000009e-15 8.192000000000005e-10]
 [1.0000000000000008e-18 6.5536000000000055e-12]
 [1.0000000000000012e-21 5.2428800000000056e-14]
 [1.0000000000000012e-24 4.194304000000005e-16]
 [1.0000000000000015e-27 3.3554432000000044e-18]
 [1.0000000000000017e-30 2.684354560000004e-20]
 [1.0000000000000018e-33 2.147483648000004e-22]
 [1.000000000000002e-36 1.7179869184000035e-24]

In [118]:
#12)
M = 25
[2^i/i for i in 1:1:M]

25-element Vector{Float64}:
      2.0
      2.0
      2.6666666666666665
      4.0
      6.4
     10.666666666666666
     18.285714285714285
     32.0
     56.888888888888886
    102.4
    186.1818181818182
    341.3333333333333
    630.1538461538462
   1170.2857142857142
   2184.5333333333333
   4096.0
   7710.117647058823
  14563.555555555555
  27594.105263157893
  52428.8
  99864.38095238095
 190650.18181818182
 364722.0869565217
 699050.6666666666
      1.34217728e6

In [119]:
#13)
N = 30
[string("fn", string(i)) for i in 1:N]

30-element Vector{String}:
 "fn1"
 "fn2"
 "fn3"
 "fn4"
 "fn5"
 "fn6"
 "fn7"
 "fn8"
 "fn9"
 "fn10"
 "fn11"
 "fn12"
 "fn13"
 ⋮
 "fn19"
 "fn20"
 "fn21"
 "fn22"
 "fn23"
 "fn24"
 "fn25"
 "fn26"
 "fn27"
 "fn28"
 "fn29"
 "fn30"

In [120]:
#14)
n = 250
x = rand(0:999, n)
y = rand(0:999, n)

250-element Vector{Int64}:
 362
 651
 205
 425
 905
 475
 190
 939
 820
 822
 597
 251
 511
   ⋮
 345
 320
 136
 317
  20
 205
 399
 834
 130
 800
 180
 828

In [121]:
[y[i+1]-x[i] for i in 1:n-1]

249-element Vector{Int64}:
  554
 -618
 -421
  238
   24
  168
  215
  172
  259
 -191
 -157
 -469
 -833
    ⋮
  -60
 -442
 -106
  165
 -496
 -547
 -488
  770
 -437
  683
  109
  796

In [122]:
[x[n-2]+2*x[n-1]-x[i] for i in 3:n]

248-element Vector{Int64}:
 -711
 -532
 -316
  113
 -589
 -513
 -428
 -653
 -273
 -845
 -812
 -439
   18
    ⋮
 -627
 -107
  -17
 -381
 -617
 -752
   71
 -432
   18
   64
  103
 -783

In [123]:
[sin(y[i-1])/cos(x[i]) for i in 2:n]

249-element Vector{Float64}:
 -0.6601300937044344
  1.0396471609189781
 -1.287957059948607
 -4.288536785917236
 -0.21952208609748033
 -4.248217489539866
  1.481595686747271
 -0.4159697163707091
  0.051645077729180824
 -0.9691530321343063
  0.0987836690021917
  1.7011892063534413
 -1.4393997926578683
  ⋮
 -1.2930981885868857
  0.5465846025946713
 -1.1924863971287591
 -1.1105433496420303
 -0.7409790344605799
  1.90451099365609
 -1.824382586954184
 -0.30869330656435034
  1.3750813882088726
  3.009830233868485
  1.0716190537438743
 -1.0101771371185286

In [125]:
s = 0
for i in 1:n-1
    s = s + exp(-x[i+1])/(x[i]+10)
end
s

0.001205313713794068

In [130]:
y600 = [y[i] for i in 1:n if (y[i]>600)]

99-element Vector{Int64}:
 651
 905
 939
 820
 822
 900
 874
 816
 979
 747
 658
 951
 848
   ⋮
 899
 694
 926
 759
 900
 948
 954
 702
 674
 834
 800
 828

In [131]:
ind = findall(y .> 600)

99-element Vector{Int64}:
   2
   5
   8
   9
  10
  16
  17
  20
  23
  26
  27
  28
  29
   ⋮
 214
 215
 217
 219
 221
 225
 228
 232
 233
 246
 248
 250

In [132]:
[x[i] for i in ind]

99-element Vector{Int64}:
 823
 451
 648
 563
 788
 179
 945
 354
 883
 482
 609
 937
 717
   ⋮
 913
 553
  87
 836
 696
 847
 447
 300
 492
 567
  71
 918

In [133]:
avg_x = sum(x)/length(x)
[sqrt(abs(x[i]-avg_x)) for i=1:n]

250-element Vector{Float64}:
 20.355834544424848
 17.65332829808589
 18.2931681236466
 12.475576139000555
  7.7691698398220135
 22.121482771279144
 14.582180906846547
 11.689311356961966
  7.186097689288672
 16.632498309033434
 10.166612021711067
 21.648094604375693
 20.87199080107118
  ⋮
 15.831613941730641
 16.412190591142913
 18.956792977716457
  2.1540659228537984
 15.512575543732252
 19.381434415439948
 21.15088650624366
  7.459222479588606
 19.85849943978648
 20.984756372185977
 21.894291493446413
 20.16531675922796

In [135]:
y_avg = sum(y)/length(y)
length([y[i] for i=1:n if (abs(y[i]-y_avg)<=200 && y[i]<y_avg)])

51

In [137]:
even_x = length([x[i] for i=1:n if (x[i]%2==0)])
uneven_x = length([x[i] for i=1:n if (x[i]%2!=0)])
even_x, uneven_x

(130, 120)

In [138]:
length([x[i] for i=1:n if (x[i]%7==0)])

37

In [152]:
y_sorted = sort!(y)
y_s_ind = [ indexin(y_sorted[i],y)[1] for i=1:n]
x_s = [x[i] for i in y_s_ind]

250-element Vector{Int64}:
  97
 823
 846
 667
 451
  22
 724
 724
 563
 788
 408
 408
 947
   ⋮
 762
 242
 152
 516
 752
 887
  64
 567
 567
  71
  32
 918

In [153]:
sort!(x, rev=true)[1:10]

10-element Vector{Int64}:
 998
 992
 987
 984
 981
 980
 980
 973
 961
 947

In [154]:
unique(x)

226-element Vector{Int64}:
 998
 992
 987
 984
 981
 980
 973
 961
 947
 946
 945
 937
 926
   ⋮
  49
  48
  44
  40
  32
  31
  24
  22
  18
  11
  10
   0

In [155]:
#4)
squares = [i^2 for i=1:100]

100-element Vector{Int64}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [157]:
#5)
using Primes
myprimes = [prime(i) for i=1:168]

168-element Vector{Int64}:
   2
   3
   5
   7
  11
  13
  17
  19
  23
  29
  31
  37
  41
   ⋮
 919
 929
 937
 941
 947
 953
 967
 971
 977
 983
 991
 997

In [158]:
myprimes[89]

461

In [159]:
myprimes[89:99]

11-element Vector{Int64}:
 461
 463
 467
 479
 487
 491
 499
 503
 509
 521
 523

In [160]:
#6.

#1)
s = 0
for i=10:100
    s = s + i^3+4*i^2
end
s

26852735

In [161]:
#2)
M = 25
s = 0
for i=1:M
    s = s + 2^i/i + 3^i/i^2
end
s

2.1291704368143802e9

In [162]:
#3)
s = 1
t = 1
for i=2:2:38
    t = t * i / (i+1) 
    s = s + t
end
s

6.97634613789762